// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD720pASYeCwVKbCSLFhbAxobV2IIYhHkU',
    appId: '1:466320078892:web:9bc33f8285f485cdd87989',
    messagingSenderId: '466320078892',
    projectId: 'term-project-4f697',
    authDomain: 'term-project-4f697.firebaseapp.com',
    storageBucket: 'term-project-4f697.appspot.com',
    measurementId: 'G-QQPVBC7DWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGGHSMmgXL47iku3Bp_ieGAbYM7y9oXWk',
    appId: '1:466320078892:android:e077d0d157175557d87989',
    messagingSenderId: '466320078892',
    projectId: 'term-project-4f697',
    storageBucket: 'term-project-4f697.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjGnjJ6n_CF6oirKPL-zlGzK7a1smaQOc',
    appId: '1:466320078892:ios:9ba108ffba0bfadcd87989',
    messagingSenderId: '466320078892',
    projectId: 'term-project-4f697',
    storageBucket: 'term-project-4f697.appspot.com',
    iosBundleId: 'com.example.termProject',
  );
}
